### ISSUE TITLE
インストール時に'ask_user'のインポートに失敗する

### ISSUE THREAD

**Issue by ghost** [pashango2/sphinx-qsp#13]
`pip install sphinx-quickstart-plus`を実行した際に、以下のようにエラーが出てインストールが失敗します。

```
Collecting sphinx-quickstart-plus
  Downloading sphinx-quickstart-plus-0.6.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/07/vwm1dqbj6v14fw0d1h_dg5100000gn/T/pip-build-qgeoex32/sphinx-quickstart-plus/setup.py", line 9, in <module>
        import sphinx_qsp
      File "/private/var/folders/07/vwm1dqbj6v14fw0d1h_dg5100000gn/T/pip-build-qgeoex32/sphinx-quickstart-plus/sphinx_qsp/__init__.py", line 4, in <module>
        from .quickstart_plus import main, __version__
      File "/private/var/folders/07/vwm1dqbj6v14fw0d1h_dg5100000gn/T/pip-build-qgeoex32/sphinx-quickstart-plus/sphinx_qsp/quickstart_plus.py", line 32, in <module>
        from sphinx.quickstart import ask_user, generate, do_prompt, nonempty, boolean
    ImportError: cannot import name 'ask_user'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/07/vwm1dqbj6v14fw0d1h_dg5100000gn/T/pip-build-qgeoex32/sphinx-quickstart-plus/
```

* macOS 10.13.3
* Python 3.6.1
を利用しています

**Comment by Rowing0914** [comment]
is this fixed??
I am still getting same error..

Env
macOS: 10.12.6
Python: 3.6.5

**Comment by Rowing0914** [comment]
I believe that I could solve the issue in this PR.
please feel free to refer to here!

https://github.com/pashango2/sphinx-qsp/pull/14
